M48
; DRILL file {KiCad 8.0.7} date 2025-03-02T22:24:46-0500
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2025-03-02T22:24:46-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.7
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1063
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1250
%
G90
G05
T1
X0.99Y-1.44
X0.99Y-7.25
X5.8Y-1.44
X5.8Y-7.25
T2
X0.95Y-4.86
X0.95Y-6.96
X5.85Y-4.86
X5.85Y-6.96
M30
